name: Schedule menu
on:
  schedule:
    - cron: "30 8 * * 1,2,3,4,5"
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          yarn
      - name: Report the menu
        env: # Or as an environment variable
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          MODULE_ID: ${{ secrets.MODULE_ID }}
        run: |
          yarn report-menu
